# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'GLWeiBo_Swift' do
use_frameworks!

pod "AFNetworking"
pod "SDWebImage"
pod "YYModel"
pod "FMDB"
pod "SVProgressHUD"
pod "pop"

end
