# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '010-表情包数据' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 010-表情包数据

  pod 'YYModel'

end
