# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'day11-001-表情键盘' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for day11-001-表情键盘

  pod 'YYModel'

end
